// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroTicketsDetalle.Server.DAL;

#nullable disable

namespace RegistroTicketsDetalle.Server.Migrations
{
    [DbContext(typeof(TicketContexto))]
    [Migration("20231022222100_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("RegistroTicketsDetalle.Shared.Tickets", b =>
                {
                    b.Property<int>("TicketsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("SolicitadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TicketsId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("RegistroTicketsDetalle.Shared.TicketsDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emisor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TicketsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TicketsId");

                    b.ToTable("TicketsDetalle");
                });

            modelBuilder.Entity("RegistroTicketsDetalle.Shared.TicketsDetalle", b =>
                {
                    b.HasOne("RegistroTicketsDetalle.Shared.Tickets", null)
                        .WithMany("TicketsDetalles")
                        .HasForeignKey("TicketsId");
                });

            modelBuilder.Entity("RegistroTicketsDetalle.Shared.Tickets", b =>
                {
                    b.Navigation("TicketsDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
